### ISSUE TITLE
Use ['load'] instead of .load to avoid conflicts with other #load method definitions

### ISSUE THREAD

**Issue by rsim** [smparkes/env-js#10]
In Rails 3 master.load was giving exception "ArgumentError: wrong number of 
arguments (0 for 1)" - it seems that somehow different #load method definition 
was called before method_missing which handles dynamic properties.

Made a patch for it http://github.com/rsim/env-js/commit/46706f1ec0131f972d346077f8bfd8ce6bd45406

Please merge it in :)

**Comment by smparkes** [comment]
Done. Feel free to send pull requests. If my fork was the top level, I think it'd be easy enough to do the pull even w/o a pull request but since I'm not, can't quite figure out how to get github to let me.

And sorry for the delay. Expect to cut a release soon.

**Comment by smparkes** [comment]
Done. Same comments as the last issue.
