### ISSUE TITLE
Check if parent is not null before accessing tagName property

### ISSUE THREAD

**Issue by rsim** [smparkes/env-js#11]
If radio input was used outside form (e.g. in jquery.rating read-only radio 
inputs are used outside form to display rating) then parent was null and was 
giving exception when accessing tagName property.

Made a patch for it http://github.com/rsim/env-js/commit/3a7335ceeeac55c830702d0ad86f5f236a115f9d

Please merge it in :)

**Comment by smparkes** [comment]
Hmmm ... thought I commented on this. Committed. Feel free to send pull requests. And sorry for the delay.
