### ISSUE TITLE
cannot set readonly attribute: type" when setting innerHtml

### ISSUE THREAD

**Issue by thechrisoshow** [smparkes/env-js#12]
Try this out:

1) Fire up envjsrb
2) Fill in the following:

newDiv = document.createElement("div");
newDiv.innerHTML = "<select multiple='multiple'></select>";

3) An exception is raised: "cannot set readonly attribute: type"

JQuery sets innerHTML to "<select multiple='multiple'></select>" when
updating the options of a select tag using append, so this been a bit
of pain in the heiney.

**Comment by smparkes** [comment]
Didn't you send me a pull request for this? I don't see anything in your repo with a fix?

**Comment by smparkes** [comment]
Blah. Never mind. The pull request ended up coming from the master branch. I see the stuff on the envjsrb branch.

**Comment by smparkes** [comment]
Think this is fixed. Don't know why I didn't close it.
