### ISSUE TITLE
URI.parse breaks using RVM and gemset

### ISSUE THREAD

**Issue by carlosantoniodasilva** [smparkes/env-js#13]
As RVM creates folders using the % sign to separate ruby version and gemset, it breakes URI.parse:

```
~/.rvm/gems/ruby-1.8.7-p249%rails3
```

I have updated envjs to use URI.escape before parsing the file name, so it will escape the % sign. Tests pass here after this change, but I don't know how I could add a test to it.

I'm sending a pull request with the changes in my fork, please take a look.
Thanks, Carlos

**Comment by smparkes** [comment]
Thanks! Should be able to get to it tomorrow ....

**Comment by carlosantoniodasilva** [comment]
Nice, thanks.

**Comment by smparkes** [comment]
Yuck.

I think this will result in double escaping for real URLs that have escape sequences in them.

Could you look at maybe catching the exception that URI.parse throws and in that specific case, creating a file URI, sort of like the heuristic is doing now?

**Comment by carlosantoniodasilva** [comment]
Hum... okay.. I'll take a look on that... 
Thanks.

**Comment by carlosantoniodasilva** [comment]
Steven, I noticed by updating my rvm installation (a bit old huh?) that it now uses @ instead of %, so it won't break with env-js anymore. So the solution is to update rvm.
I guess you can close this issue.
Thanks for your help and time.

**Comment by smparkes** [comment]
Cool. Good to avoid %s in filenames (hadn't thought of that before); glad RVM got tweaked.

envjs should probably allow %'s in paths that dont' start as URIs, but we can make it lower priority.
