### ISSUE TITLE
Unable to visit HTTPS sites

### ISSUE THREAD

**Issue by heathkit** [smparkes/env-js#14]
If I try to go to an https-only site in env-js with Ruby 1.8.6, I get an error from Net::HTTP because the connection isn't using SSL.  The following simple patch fixes that, though I'm sure there are other, related issues.

<pre>
diff --git a/src/platform/johnson.js b/src/platform/johnson.js
index 491ad16..4962fb4 100644
--- a/src/platform/johnson.js
+++ b/src/platform/johnson.js
@@ -131,6 +131,7 @@ $env.connection = $master.connection || function(xhr, responseHandler, da
         }
     } else { 
         Ruby.eval("require 'net/http'");
+        Ruby.eval("require 'net/https'");
 
         var req;
         var path;
@@ -160,7 +161,9 @@ $env.connection = $master.connection || function(xhr, responseHandler, da
        }
        
         try {
-            connection = Ruby.Net.HTTP.start( url.host, url.port );
+            connection = Ruby.Net.HTTP.new( url.host, url.port );
+            connection.use_ssl = ( url.scheme == "https" );
+            connection.start();
             resp = connection.request(req);
         } catch(e) {
             $env.warn("XHR net request failed: "+e);
</pre>

**Comment by smparkes** [comment]
Thanks! Slightly tweaked to avoid requiring net/https unless necessary (on the off chance someone doesn't have it?)
