### ISSUE TITLE
Serialize multipart/form-data forms correctly

### ISSUE THREAD

**Issue by h-lame** [smparkes/env-js#16]
When serializing multipart/form-data we need to separate the headers for a part from the data value with a blank newline. e.g:

Content-Disposition: form-data; name="username"

jresig

note:

Content-Disposition: form-data; name="username"
jresig

which is what happens currently.

Fix available here: http://github.com/h-lame/env-js/commit/38e63ddf37c980ed323ea27e9df2f62b5f069dfb
Tests available here: http://github.com/h-lame/env-js/commit/87a1728d91aa67cad4e54bf28dcba2a991ff6cec

**Comment by smparkes** [comment]
Looks good. Thanks!
