### ISSUE TITLE
$w is not defined exception when calling visit a second time

### ISSUE THREAD

**Issue by tylerkovacs** [smparkes/env-js#17]
I'm using capybara-0.3.9, capybara-envjs-0.1.6 and envjs-0.3.7.  It works perfectly if I have a single test case that only invokes visit once.  But if I invoke visit a second time (either in the same test case or in separate ones), I get the following exception:

$ ruby spec/acceptance/raw_javascript_track_spec.rb
WARNIING:     [Sat Jul 31 2010 08:41:25 GMT-0700 (PST)] {ENVJS} Exception while loading window: ReferenceError: $w is not defined
F

1)
Johnson::Error in 'Feature name
  In order to ...
  As a ...
  I want to ...
 should include bucket javascript on the page'
$w is not defined
vendor/gems/envjs-0.3.7/lib/envjs/static.js:22590 [JavaScript]
vendor/gems/envjs-0.3.7/lib/envjs/static.js:22580 [JavaScript]
vendor/gems/envjs-0.3.7/lib/envjs/static.js:3654 [JavaScript]
vendor/gems/envjs-0.3.7/lib/envjs/env.js:1145 [JavaScript]
vendor/gems/envjs-0.3.7/lib/envjs/env.js:2665 [JavaScript]
vendor/gems/envjs-0.3.7/lib/envjs/env.js:95 [JavaScript]
vendor/gems/envjs-0.3.7/lib/envjs/env.js:2674 [JavaScript]
vendor/gems/envjs-0.3.7/lib/envjs/env.js:6 [JavaScript]
vendor/gems/envjs-0.3.7/lib/envjs/runtime.rb:53:in `evaluate'
vendor/gems/envjs-0.3.7/lib/envjs/runtime.rb:189:in`extended'
vendor/gems/capybara-envjs-0.1.6/lib/capybara/driver/envjs_driver.rb:190:in `call'
vendor/gems/capybara-envjs-0.1.6/lib/capybara/driver/envjs_driver.rb:190:in`initialize'
vendor/gems/envjs-0.3.7/lib/envjs/env.js:596 [JavaScript]
vendor/gems/envjs-0.3.7/lib/envjs/env.js:606 [JavaScript]
vendor/gems/envjs-0.3.7/lib/envjs/env.js:1887 [JavaScript]
vendor/gems/envjs-0.3.7/lib/envjs/env.js:1936 [JavaScript]
vendor/gems/capybara-envjs-0.1.6/lib/capybara/driver/envjs_driver.rb:254:in `visit'
vendor/gems/capybara-0.3.9/lib/capybara/dsl.rb:55:in`visit'
spec/acceptance/raw_javascript_track_spec.rb:21:

**Comment by smparkes** [comment]
Hmmm ... do you have an example I can run? These things are difficult to track down without an example ...

**Comment by dmcinnes** [comment]
I'm having a similar issue when I create a cookie then try to open a new window:

document.cookie = 'foo';
window.open('blank.html');

and the error:

WARNIING:   [Mon Sep 13 2010 17:26:25 GMT-0700 (PST)] {ENVJS} Exception while loading window: ReferenceError: $w is not defined
envjs-0.3.7/lib/envjs/static.js:22587 [JavaScript]: $w is not defined (Johnson::Error)

**Comment by smparkes** [comment]
What is blank? A valid minimal doc?

**Comment by dmcinnes** [comment]
Yeah, here it is:

<html>
    <head>
    </head>
    <body>
    </body>
</html>

**Comment by dmcinnes** [comment]
d'oh it cut of the html tags :-\  just pretend there are opening and closing html tags around that

**Comment by smparkes** [comment]
Fixed in 28ff2a6f6f7092eae959730c4cea7351f81b9c68.

**Comment by smparkes** [comment]
Actually, the cookie issue and the original issue are likely different. The fix is for the cookie issue and is in 0.3.8.

**Comment by tylerkovacs** [comment]
My apologies for not participating on this thread sooner - I filed the bug while working on a project that has since been dropped.  The original issue was related to the use of cookies so it may be one and the same.

**Comment by smparkes** [comment]
> I filed the bug while working on a project that has since been dropped

No worries. I know the feeling. I'll close this and we can create another issue if something comes up.

**Comment by dmcinnes** [comment]
Cool, thanks!
