### ISSUE TITLE
timer error: TypeError: $events[target.uuid] is undefined

### ISSUE THREAD

**Issue by orslumen** [smparkes/env-js#18]
Hello Steven,

First of all thanks for your efforts, I really appreciate being able to do proper integration testing, including JS.

Today, I ran into the following issue with the `$events` hash:

```
timer error: TypeError: $events[target.uuid] is undefined
timer error: __removeEventListener__([object Object],"keydown")@/home/orslumen/.bundle/ruby/1.8/gems/envjs-0.3.7/lib/envjs/env.js:2158
("keydown",(function () {return typeof jQuery !== "undefined" && !jQuery.event.triggered ? jQuery.event.handle.apply(eventHandle.elem, arguments) : undefined;}),false)@/home/orslumen/.bundle/ruby/1.8/gems/envjs-0.3.7/lib/envjs/static.js:1714
([object Object],"keydown",(function () {return typeof jQuery !== "undefined" && !jQuery.event.triggered ? jQuery.event.handle.apply(eventHandle.elem, arguments) : undefined;}))@inline:2070
...
()@/home/orslumen/.bundle/ruby/1.8/gems/envjs-0.3.7/lib/envjs/event_loop.js:67
(0)@/home/orslumen/.bundle/ruby/1.8/gems/envjs-0.3.7/lib/envjs/event_loop.js:153
(-1989.672)@/home/orslumen/.bundle/ruby/1.8/gems/envjs-0.3.7/lib/envjs/env.js:2121
```

In my case this was the result of a jQuery submit handler with a timeout, something like:

```
$('#my_form_id').submit(function() {
  window.setTimeout(function() {
    $('#some_element_with_bindings').unbind();
  }, 100);
  return true;
});
```

I think the actual submit clears the `$events` hash and then, 100 milliseconds later, the `$events[target.uuid]` can not be found anymore. Probably this behaviour is correct, but I would like env.js not to throw an error at me.

Locally I have fixed this by adding the 3 lines of code to ****removeEventListener****:

```
function __removeEventListener__(target, type, fn){
  if ( !target.uuid ) {
    target.uuid = $events.length;
    $events[target.uuid] = {};
  }
  // do not throw an error in case an event is removed from a non-existing element
  if (!$events[target.uuid]) {
    return;
  }
  if ( !$events[target.uuid][type] ){
  ...
```

As I have not spend that much time in **env.js** I am not sure if this is the right fix (it works for me :) In case the fix can be applied in general, I would appreciate it if you could add it to the codebase for the following release.

PS. I am using:
  johnson (2.0.0.pre3)
  capybara-envjs (0.1.6)
  envjs (0.3.7)

**Comment by smparkes** [comment]
Agreed. Thanks.
