### ISSUE TITLE
debug is not defined in $env.log()

### ISSUE THREAD

**Issue by fiann** [smparkes/env-js#19]
I found this when loading a script by inserting a DOM script node, and the script URL gives a 404.

Here's the relevant part of the stack trace:

```
Exception: TypeError: debug is not a function
/opt/local/lib/ruby/gems/1.8/gems/envjs-0.3.7/lib/envjs/env.js:148 ("could not load script http://localhost/core/javascripts/script-loader-badfile.js: 404 Not Found","...
/opt/local/lib/ruby/gems/1.8/gems/envjs-0.3.7/lib/envjs/env.js:693 ("could not load script http://localhost/core/javascripts/script-loader-badfile.js: 404 Not Found")
/opt/local/lib/ruby/gems/1.8/gems/envjs-0.3.7/lib/envjs/env.js:816 ([object Object],null)
```

The reason is that `$env.log()` calls `debug()` not `print()`

**Comment by fiann** [comment]
There's a fix here. http://github.com/fiann/env-js/commit/72fc80bf1e5b09b2e2dbd3003b0a49998922bbb1

Changing this outputs a lot of additional warnings when running the build, which may or may not matter.

**Comment by smparkes** [comment]
Thanks.

The build's always printed a lot of warnings, I think.
