### ISSUE TITLE
"$w is not defined" error when setting a cookie with a domain

### ISSUE THREAD

**Issue by dmcinnes** [smparkes/env-js#20]
thanks for the other cookie fix, but I'm having a similar issue when setting cookies now if they have a domain:
document.cookie = 'foo=bar; expires=Mon, 13 Sep 2010 22:14:13 GMT; path=/; domain=baz.com';

gives this error:

envjs-0.3.8/lib/envjs/static.js:23039 [JavaScript]: $w is not defined (Johnson::Error)

I appears to be using the $w static as well, I changed that line to:
cookie['domain']=this._parentWindow.location.domain;

Real edge case, but I thought I'd open a ticket for it.

Thanks for the awesome gem!

**Comment by smparkes** [comment]
Yeah, I guess I should have fixed it then, too, but I wanted to wait and see if anyone was actually using it.

I'm not 100% sure how functional the cookie code is, to be honest.

I put the patch in but I may wait a day or two before pushing a new gem.

**Comment by dmcinnes** [comment]
I may be the only one :)
I'm using it to test our site code with jspec and we set a couple cookies in one of our libraries
Thanks for the quick response!
