### ISSUE TITLE
'timer error' raised from event_loop.js

### ISSUE THREAD

**Issue by chrisroos** [smparkes/env-js#23]
I've got a fairly complete example of the problem in https://github.com/chrisroos/capybara-envjs-rack-test.  I haven't had a go at writing a failing test or a fix.  The reason is that the rhino version of envjs doesn't suffer from this same problem and I think it'd be a better use of time to bring the two versions back in sync rather than fixing specific problems in this version.  I'm going to follow this up on the mailing list too, to see whether I can be of any help in bringing the versions back in sync.

**Comment by smparkes** [comment]
Fixed.

**Comment by smparkes** [comment]
4307aa7b70af992f5e1d60fc736d0ba8c34649c6

**Comment by chrisroos** [comment]
Hey, that's great, cheers Steven.  Just one thing though...  Although I no longer get the 'timer error', clicking the link to visit a fragment doesn't update the window.location as I'd expect.

You may have already seen it but I've posted a message to the envjs group[1] asking whether I can help get the johnson version of envjs back into line with the rhino version.

[1] http://groups.google.com/group/envjs/browse_thread/thread/ec2ba83d0fb3e57c

**Comment by smparkes** [comment]
I'm not sure about the hash thing. If I print window.location in your renderAjaxReponse, I get the url with the hash and did a quick code inspection of the relevant paths, and they should be setting the url. Do you have a test case?

Also, I've never seen the double location set issue you mentioned in the git repo. Does the right thing for me first time and doesn't print the errors.

**Comment by chrisroos** [comment]
Ah, you're right.  I did have a failing test[1] but the test itself wasn't quite right.  I was using Capybara's current_path method which obviously ignores the fragment part of the URL.  I changed the test to use current_url and can see that the fragment is indeed appended to the URL.  Cheers for your help Steven.

[1] https://github.com/chrisroos/capybara-envjs-rack-test/blob/master/test/envjs_rack_app_test.rb
