### ISSUE TITLE
scripts added after page load

### ISSUE THREAD

**Issue by trevorh** [smparkes/env-js#5]
Hello,

I was curious if you'll be merging this particular change in.

http://envjs.lighthouseapp.com/projects/21590/tickets/82-execution-of-scripts-added-after-page-load

I'm hoping it would solve an issue we've encountered within Harmony which uses your gem.

Best,
Trevor

**Comment by trevorh** [comment]
http://github.com/thatcher/env-js/commit/88c570151c507eddb74e87317a1ebd55aa2daee2 

It's that particular commit but I don't know how much it depends on prior commits.

**Comment by smparkes** [comment]
I'd be happy to cherry-pick the change if I can figure out what it is. With all the rework that's going on, that's not the easiest thing in the world ...

How did you identify this commit? From the commit comment? Looking at the commit itself, I'm not sure I see anything that would change the behavior.

**Comment by smparkes** [comment]
I found the commit where master does this ...

**Comment by smparkes** [comment]
Actually, I'm not sure this is your problem. It sounds like you weren't sure? The reason being that I don't think Spidermonkey fork of envjs has this issue. Chris mentioned that it originally worked and I just checked and scripts added to the DOM after doc load do get executed.

There are a number of corner cases that aren't covered, but I'm not sure if you're hitting one of those, and if you are, which one.

Do you have an example that doesn't' work and how it fails?

**Comment by trevorh** [comment]
Steven,

Thanks for the quick responses.

Based on something I read today, I'm not so sure the change I referenced above will help me.

I had been loading my scripts as text/envjs but it seems Harmony and/or your gem don't care about that. It seems JSON.stringify is loaded no matter what which confused me and made me think the scripts were loading when in fact neither the Google nor Crockford script was.

<pre><code>$ irb
>> require 'harmony'
=> true
>> page = Harmony::Page.new
=> #<Harmony::Page:0x5a094c>
>> page.execute_js("JSON.stringify(5)")
=> "5"
>> </code></pre>

I guess this is part of the envJS environment?

Now I get an error:  <blockquote>WARNIING:  [Thu Mar 11 2010 09:40:49 GMT-0500 (EST)] {ENVJS} The Google Maps API server rejected your request. The "sensor" parameter specified in the request must be set to either "true" or "false".</blockquote>

Now, that I've been loading them as text/javascript - one of the issues is referenced here http://groups.google.com/group/envjs/browse_thread/thread/4ba2d38b22f7d2d9 which Thatcher seems to have fixed by his reply on Feb 5th at 9:25a - having a URL parameter in the script src.

Next, Someone on the envJS list was trying to do the same thing I was both in that thread and here: http://groups.google.com/group/envjs/browse_thread/thread/af76ef49943c38a9

I was trying to see if Harmony would allow us to do geocoding and directions server-side via the Maps JS API.

http://gist.github.com/329218

That's an example that works in a browser currently. But won't work in Harmony because of the parameter required to load the Google script.

However, based on the first Google Groups thread's last message, I'm thinking envJS still won't able to fully load the Maps API.

Thoughts?

Trevor

**Comment by smparkes** [comment]
The text/envjs thing is new. I don't use it so I haven't pulled it.

JSON is part of ES5 and is actually implemented in native code in Spidermonkey, so you'll always get it. The standard json2.js will detect this and not do anything, so you can always load it if you want.

I'll look up the other stuff. I make fixes to the env.js URL stuff as I come across them. There were a number when I did the Capybara env.js driver.

Thanks for the example page: makes it a lot easier to track down stuff.

**Comment by smparkes** [comment]
The json2.js fetch error is interesting. That server requires HTTP/1.1 and I'm not sure we're sending that correctly. Let me check.

**Comment by trevorh** [comment]
Fetch error? I don't think I ever saw a fetch error. I saw this warning which is just the alert that Crockford placed into the file.
<code> WARNIING:    [Thu Mar 11 2010 09:40:49 GMT-0500 (EST)] {ENVJS} IMPORTANT: Remove this line from json2.js before deployment.</code>

I tried playing with Rhino and envJS this morning but I don't think I either set up the Rhino shell correctly or didn't use the right sequence of method calls.

**Comment by smparkes** [comment]
Yeah, you only get the fetch error if you run envjsrb interactively. What the heck's up with that? :)

It is a nice way to debug this stuff, so I want to make it work.

**Comment by smparkes** [comment]
As of the latest commit, the GM example now works. see the gm directory (at least for now ...). I haven't released a gem of this yet. Can you just build it/install it locally?

I have no comment on whether this is allowed under Google's terms of service. I just wanted to figure out why the scripts didn't work.
